In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/Week 1 GA.csv')

In [ ]:
data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [ ]:
data.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [ ]:
for col in col_list:
  print(data[col].value_counts().get('?', 0))

0
0
0
0
0
0
0
0
0
0
0
0

In [ ]:
col_list = data.columns.to_list()
count_question = 0
for col in col_list:
  check = len(data[data[col] == '?'])
  print(check)
  count_question = count_question + check
count_question

0
0
0
0
0
1823
0
0
0
0
0
0

1823

In [ ]:
data.loc[data['Property'] == '?', 'Property'] = np.nan

In [ ]:
data.shape

(10000, 12)

In [ ]:
data.iloc[692, 0]

'2009-11-16'

In [ ]:
data.iloc[546, 7]

3

In [ ]:
data['Locality'].unique()

array(['Waterbury', 'Bridgeport', 'Greenwich', 'Norwalk', nan,
       'Fairfield', 'West Hartford', 'Stamford'], dtype=object)

In [ ]:
data.iloc[4, :].isna().sum()

1

In [ ]:
new_data = data.dropna(axis = 0, thresh = data.shape[1]-2)
new_data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [ ]:
new_data_2 = data.dropna(axis = 0)
new_data_2

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
...,...,...,...,...,...,...,...,...,...,...,...,...
9986,2022-09-28,2022,Norwalk,305820.0,535000.0,Single Family,Detached House,3,2,1080.0,1.003979,West
9987,2022-09-28,2022,Norwalk,450510.0,677000.0,Single Family,Detached House,3,1,1000.0,1.003979,North
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [42]:
data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [44]:
even_index = data.iloc[::2]
even_index.iloc[0, 3]

111440.0

In [45]:
even_index.iloc[332, 3]

256200.0

In [49]:
odd_index = data.iloc[1::2,]
odd_index

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North
9,2009-01-02,2009,Bridgeport,137901.0,245000.0,Single Family,Detached House,3,1,956.0,1.025953,West
...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2022-09-30,2022,Norwalk,344270.0,512500.0,Single Family,Detached House,3,3,NaN,1.003979,West
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [47]:
odd_index.iloc[332, 3]

352940.0

In [48]:
odd_index.iloc[100, 5]

'Single Family'

In [50]:
even_index_2 = data.iloc[::2, ::2]
even_index_2

,Date,Locality,Sale Price,Residential,num_bathrooms,property_tax_rate
0,2009-01-02,Waterbury,185000.0,Detached House,3,1.025953
2,2009-01-02,Waterbury,140000.0,Detached House,2,1.025953
4,2009-01-02,Bridgeport,210000.0,Detached House,2,1.025953
6,2009-01-02,Norwalk,1000000.0,Detached House,2,1.025953
8,2009-01-02,NaN,1680000.0,Detached House,1,1.025953
...,...,...,...,...,...,...
9990,2022-09-30,NaN,700000.0,Detached House,3,1.003979
9992,2022-09-30,Fairfield,680000.0,Detached House,2,1.003979
9994,2022-09-30,NaN,215000.0,Triplex,5,1.003979
9996,2022-09-30,Bridgeport,340000.0,Duplex,4,1.003979
9998,2022-09-30,NaN,415000.0,Detached House,3,1.003979

In [51]:
even_index_2.iloc[255, 3]

'Detached House'

In [56]:
last_6_years = sorted(data['Year'].unique(), reverse = True)[:6]
last_6_years_df = data[data['Year'].isin(last_6_years)]
last_6_years_df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
5251,2017-01-02,2017,Waterbury,40350.0,42000.0,Three Family,Triplex,6,6,2076.0,1.388283,West
5252,2017-01-05,2017,NaN,388450.0,560000.0,Single Family,Detached House,3,3,1033.0,1.388283,North
5253,2017-01-05,2017,NaN,164710.0,179900.0,Single Family,Detached House,3,1,NaN,1.388283,South
5254,2017-01-06,2017,Norwalk,222030.0,375000.0,Single Family,Detached House,3,3,989.0,1.388283,West
5255,2017-01-06,2017,Bridgeport,173780.0,215000.0,NaN,Detached House,3,3,929.0,1.388283,West
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [59]:
select_df = data[(data['num_rooms'] == 3) | (data['num_bathrooms'] == 3)]
select_df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [62]:
select_complex_df = data[(data['Year'] == 2022) & (data['Locality'] == 'Greenwich') & (data['num_rooms'] == 3) & (data['Face'].isin(['North', 'East']))]
select_complex_df.shape

(42, 12)

In [65]:
data['Date'] = pd.to_datetime(data['Date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  datetime64[ns]
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   object
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           8177 non-null   object
 6   Residential        10000 non-null  object
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(3), object(4)
memory usage: 937.6+ KB

In [67]:
august_df = data[data['Date'].dt.month == 8]
august_df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
500,2009-08-01,2009,Greenwich,919800.0,1275000.0,Single Family,Detached House,3,1,NaN,1.025953,North
501,2009-08-01,2009,Fairfield,417130.0,505000.0,Single Family,Detached House,3,3,1011.0,1.025953,South
502,2009-08-01,2009,Fairfield,NaN,420000.0,Single Family,Detached House,3,3,976.0,1.025953,East
503,2009-08-01,2009,Norwalk,257950.0,460000.0,Single Family,Detached House,3,3,966.0,1.025953,East
504,2009-08-01,2009,Norwalk,239330.0,400000.0,Single Family,Detached House,3,2,973.0,1.025953,South
...,...,...,...,...,...,...,...,...,...,...,...,...
9862,2022-08-31,2022,Bridgeport,123720.0,230000.0,Single Family,Detached House,3,1,1084.0,1.003979,North
9863,2022-08-31,2022,Stamford,438680.0,472500.0,Single Family,Detached House,3,1,NaN,1.003979,South
9864,2022-08-31,2022,NaN,57760.0,120000.0,NaN,Triplex,6,5,2156.0,1.003979,West
9865,2022-08-31,2022,Fairfield,314650.0,287000.0,Single Family,Detached House,3,3,1012.0,1.003979,West
9866,2022-08-31,2022,Stamford,347990.0,579000.0,Single Family,Detached House,3,1,NaN,1.003979,North

In [70]:
data1 = data

In [73]:
avg_locality = data1.groupby('Locality')['Sale Price'].mean()
avg_locality.idxmax()

'Greenwich'